version: '3.1'
services:
  ju_hub:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports: 
      - "8888:8888"
    volumes: 
      - .:/home/jovyan
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports: 
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes: 
  pgdata:
